### ISSUE TITLE
Update according to the instructions given.

### ISSUE THREAD

**Issue by modihere** [modivivek/updated-squawka-crawler#1]
Remove the file squwaka.py from the repository.
Change the name of squwaka1.py to PlayerCrawler(step 1).py and of squwaka2.py to StatsCrawler(step 2).py
Update the readme accordingly.

**Comment by ashutosh97** [comment]
I'd like to work on this one!

**Comment by ashutosh97** [comment]
Please review and merge https://github.com/lugnitdgp/updated-squawka-crawler/pull/3

**Comment by modihere** [comment]
done
