### ISSUE TITLE
Change team names. 

### ISSUE THREAD

**Issue by modihere** [modivivek/updated-squawka-crawler#2]
Update the teams array with the names of present in Champions League 2107-18 season in both the files which will crawl the website.

**Comment by shauryachawla** [comment]
Working on this one!

**Comment by modihere** [comment]
Just take care because the guy working on the other issue will change the filenames so you may have to clone again from the remote or else your PR will conflict.

**Comment by shauryachawla** [comment]
okay!

**Comment by amrs-tech** [comment]
I'm interested in updating it.

**Comment by modihere** [comment]
okay do it!

**Comment by amrs-tech** [comment]
Thanks.

**Comment by a-arpit94** [comment]
After running PlayerCrawler.py
PlayerFile.txt should still be empty??

**Comment by abkosar** [comment]
Code analysis has passed for PR #6

**Comment by modihere** [comment]
@a-arpit94 No. It will be updated but not as a normal text file i think.

**Comment by modihere** [comment]
@abkosar  please don't mind but @amrs-tech had already told that he would work on it. So accordingly his PR will be given preference. 
@abkosar There will other issues soon be updated on this repo so you can solve them or if you can find an issue and file a PR for it you are welcome to do so.

**Comment by amrs-tech** [comment]
Thanks for approving my Pull Request @modihere
